### ISSUE TITLE
Question: Why need pinToken variable is a slice, in NewUser function ? 

### ISSUE THREAD

**Issue by Kuri-su** [fox-one/mixin-sdk#12]
i saw the `NewUser()` just used `pinToken[0]`.

Is mean the pinToken variable is optional in here ?

https://github.com/fox-one/mixin-sdk/blob/master/user.go#L28

**Comment by cw35** [comment]
yes, optional. If you don't need to send PIN Required requests, you can ignore it.

**Comment by Kuri-su** [comment]
> yes, optional. If you don't need to send PIN Required requests, you can ignore it.

maybe we can use a `Option` struct to end this puzzle : ) 

like this 
```go
type Option struct{
key1 string
key2 string
key3 string
// ...
}

func NewUser(o Option){

}
